version: 2
jobs:
  build:
    docker:
      - image: determinant/inference:0.2.1
    working_directory: /usr/src/aboleth
    steps:
      - checkout
      - run: mkdir -p test_output/pytest test_output/flake8 test_output/coverage
      - run: pip3 install -e .[dev]
      - run: make coverage
      - run: make lint
      - store_artifacts:
          path: test_output/coverage
          destination: reports
      - store_test_results:
          path: test_output/
